language: cpp
sudo: required
dist: trusty
addons:
  mariadb: '10.0'
  postgresql: '9.4'
  apt:
    packages:
    - mariadb-server
    - mariadb-client
    - lcov
    - curl
    - libsqlite3-dev
    - libgtest-dev
    - libpq-dev
    - libmysqlclient-dev
    - libmozjs-24-dev

services:
  - postgresql
  - mysql

compiler:
#  - clang
  - gcc

install:
  - pushd /usr/src/gtest
  - sudo cmake -DCMAKE_BUILD_TYPE=Release .
  - sudo make VERBOSE=1
  - sudo mv libg* /usr/lib/
  - popd

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - mysql -e 'create database travis_ci_test;' -uroot
  - mkdir -p build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_SHARED_LIBS=ON -DCOVERALLS=ON -DCOVERALLS_UPLOAD=ON -DTEST_POSTGRES_DBNAME=travis_ci_test -DTEST_POSTGRES_DBUSER=postgres -DTEST_MYSQL_DBNAME=travis_ci_test -DTEST_MYSQL_DBUSER=root ..

script:
  - sqlite3 -version
  - make VERBOSE=1
  - make test
  - cat Testing/Temporary/LastTest.log
  - make package
  - sudo dpkg -i metacpp-0.3.0-Linux.deb
  - make coveralls
