language: cpp

compiler:
  - gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libjsoncpp-dev libsqlite3-dev

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make
