language: cpp

compiler:
  - gcc

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -y libjsoncpp-dev libsqlite3-dev libgtest-dev libpq-dev
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - pushd /usr/src/gtest
  - sudo cmake -DCMAKE_BUILD_TYPE=RELEASE .
  - sudo make
  - sudo mv libg* /usr/lib/
  - popd

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
  - make test
  - cat Testing/Temporary/LastTest.log
