language: cpp
sudo: required
dist: trusty

compiler:
  - gcc

install:
  - sudo apt-get install -y libjsoncpp0 libjsoncpp-dev libsqlite3-dev libgtest-dev libpq-dev libmysqlclient-dev

  - pushd /usr/src/gtest
  - sudo cmake -DCMAKE_BUILD_TYPE=Release .
  - sudo make
  - sudo mv libg* /usr/lib/
  - popd

before_script:
  - mkdir -p build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=RelMinSize -DBUILD_SHARED_LIBS=ON

script:
  - sqlite3 -version
  - make VERBOSE=1
  - make test
  - cat Testing/Temporary/LastTest.log
  - sudo make install
